/* soapContentServiceSoap12Proxy.cpp
   Generated by gSOAP 2.8.3 from plasma.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapContentServiceSoap12Proxy.h"

ContentServiceSoap12Proxy::ContentServiceSoap12Proxy()
{	ContentServiceSoap12Proxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

ContentServiceSoap12Proxy::ContentServiceSoap12Proxy(const struct soap &_soap) : soap(_soap)
{ }

ContentServiceSoap12Proxy::ContentServiceSoap12Proxy(const char *url)
{	ContentServiceSoap12Proxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

ContentServiceSoap12Proxy::ContentServiceSoap12Proxy(soap_mode iomode)
{	ContentServiceSoap12Proxy_init(iomode, iomode);
}

ContentServiceSoap12Proxy::ContentServiceSoap12Proxy(const char *url, soap_mode iomode)
{	ContentServiceSoap12Proxy_init(iomode, iomode);
	soap_endpoint = url;
}

ContentServiceSoap12Proxy::ContentServiceSoap12Proxy(soap_mode imode, soap_mode omode)
{	ContentServiceSoap12Proxy_init(imode, omode);
}

ContentServiceSoap12Proxy::~ContentServiceSoap12Proxy()
{ }

void ContentServiceSoap12Proxy::ContentServiceSoap12Proxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://www.w3.org/2003/05/soap-envelope", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://www.w3.org/2003/05/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"Plasma", "http://tempuri.org/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void ContentServiceSoap12Proxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void ContentServiceSoap12Proxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *ContentServiceSoap12Proxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *ContentServiceSoap12Proxy::soap_fault()
{	return this->fault;
}

const char *ContentServiceSoap12Proxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *ContentServiceSoap12Proxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int ContentServiceSoap12Proxy::soap_close_socket()
{	return soap_closesock(this);
}

void ContentServiceSoap12Proxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
void ContentServiceSoap12Proxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}

char *ContentServiceSoap12Proxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int ContentServiceSoap12Proxy::DownloadFile(const char *endpoint, const char *soap_action, _Plasma__DownloadFile *Plasma__DownloadFile, _Plasma__DownloadFileResponse *Plasma__DownloadFileResponse)
{	struct soap *soap = this;
	struct __Plasma__DownloadFile soap_tmp___Plasma__DownloadFile;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://zero-k.info/ContentService.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/DownloadFile";
	soap->encodingStyle = NULL;
	soap_tmp___Plasma__DownloadFile.Plasma__DownloadFile = Plasma__DownloadFile;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Plasma__DownloadFile(soap, &soap_tmp___Plasma__DownloadFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Plasma__DownloadFile(soap, &soap_tmp___Plasma__DownloadFile, "-Plasma:DownloadFile", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Plasma__DownloadFile(soap, &soap_tmp___Plasma__DownloadFile, "-Plasma:DownloadFile", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Plasma__DownloadFileResponse)
		return soap_closesock(soap);
	Plasma__DownloadFileResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Plasma__DownloadFileResponse->soap_get(soap, "Plasma:DownloadFileResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
