/* soapContentServiceSoap12Proxy.h
   Generated by gSOAP 2.7.9l from plasma.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapContentServiceSoap12Proxy_H
#define soapContentServiceSoap12Proxy_H
#include "soapH.h"

class SOAP_CMAC ContentServiceSoap12Proxy : public soap
{ public:
	/// Endpoint URL of service 'ContentServiceSoap12Proxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	ContentServiceSoap12Proxy();
	/// Constructor with engine input+output mode control
	ContentServiceSoap12Proxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	ContentServiceSoap12Proxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~ContentServiceSoap12Proxy();
	/// Initializer used by constructor
	virtual	void ContentServiceSoap12Proxy_init(soap_mode imode, soap_mode omode);
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Web service operation 'AutohostPlayerJoined' (return error code or SOAP_OK)
	virtual	int AutohostPlayerJoined(_Plasma__AutohostPlayerJoined *Plasma__AutohostPlayerJoined, _Plasma__AutohostPlayerJoinedResponse *Plasma__AutohostPlayerJoinedResponse);
	/// Web service operation 'BalanceTeams' (return error code or SOAP_OK)
	virtual	int BalanceTeams(_Plasma__BalanceTeams *Plasma__BalanceTeams, _Plasma__BalanceTeamsResponse *Plasma__BalanceTeamsResponse);
	/// Web service operation 'DownloadFile' (return error code or SOAP_OK)
	virtual	int DownloadFile(_Plasma__DownloadFile *Plasma__DownloadFile, _Plasma__DownloadFileResponse *Plasma__DownloadFileResponse);
	/// Web service operation 'GetEloByAccountID' (return error code or SOAP_OK)
	virtual	int GetEloByAccountID(_Plasma__GetEloByAccountID *Plasma__GetEloByAccountID, _Plasma__GetEloByAccountIDResponse *Plasma__GetEloByAccountIDResponse);
	/// Web service operation 'GetEloByName' (return error code or SOAP_OK)
	virtual	int GetEloByName(_Plasma__GetEloByName *Plasma__GetEloByName, _Plasma__GetEloByNameResponse *Plasma__GetEloByNameResponse);
	/// Web service operation 'GetEloTop10' (return error code or SOAP_OK)
	virtual	int GetEloTop10(_Plasma__GetEloTop10 *Plasma__GetEloTop10, _Plasma__GetEloTop10Response *Plasma__GetEloTop10Response);
	/// Web service operation 'GetRecommendedMap' (return error code or SOAP_OK)
	virtual	int GetRecommendedMap(_Plasma__GetRecommendedMap *Plasma__GetRecommendedMap, _Plasma__GetRecommendedMapResponse *Plasma__GetRecommendedMapResponse);
	/// Web service operation 'GetResourceData' (return error code or SOAP_OK)
	virtual	int GetResourceData(_Plasma__GetResourceData *Plasma__GetResourceData, _Plasma__GetResourceDataResponse *Plasma__GetResourceDataResponse);
	/// Web service operation 'GetResourceList' (return error code or SOAP_OK)
	virtual	int GetResourceList(_Plasma__GetResourceList *Plasma__GetResourceList, _Plasma__GetResourceListResponse *Plasma__GetResourceListResponse);
	/// Web service operation 'GetScriptMissionData' (return error code or SOAP_OK)
	virtual	int GetScriptMissionData(_Plasma__GetScriptMissionData *Plasma__GetScriptMissionData, _Plasma__GetScriptMissionDataResponse *Plasma__GetScriptMissionDataResponse);
	/// Web service operation 'GetSpringBattleStartSetup' (return error code or SOAP_OK)
	virtual	int GetSpringBattleStartSetup(_Plasma__GetSpringBattleStartSetup *Plasma__GetSpringBattleStartSetup, _Plasma__GetSpringBattleStartSetupResponse *Plasma__GetSpringBattleStartSetupResponse);
	/// Web service operation 'NotifyMissionRun' (return error code or SOAP_OK)
	virtual	int NotifyMissionRun(_Plasma__NotifyMissionRun *Plasma__NotifyMissionRun, _Plasma__NotifyMissionRunResponse *Plasma__NotifyMissionRunResponse);
	/// Web service operation 'RegisterResource' (return error code or SOAP_OK)
	virtual	int RegisterResource(_Plasma__RegisterResource *Plasma__RegisterResource, _Plasma__RegisterResourceResponse *Plasma__RegisterResourceResponse);
	/// Web service operation 'SubmitMissionScore' (return error code or SOAP_OK)
	virtual	int SubmitMissionScore(_Plasma__SubmitMissionScore *Plasma__SubmitMissionScore, _Plasma__SubmitMissionScoreResponse *Plasma__SubmitMissionScoreResponse);
	/// Web service operation 'SubmitSpringBattleResult' (return error code or SOAP_OK)
	virtual	int SubmitSpringBattleResult(_Plasma__SubmitSpringBattleResult *Plasma__SubmitSpringBattleResult, _Plasma__SubmitSpringBattleResultResponse *Plasma__SubmitSpringBattleResultResponse);
	/// Web service operation 'SubmitStackTrace' (return error code or SOAP_OK)
	virtual	int SubmitStackTrace(_Plasma__SubmitStackTrace *Plasma__SubmitStackTrace, _Plasma__SubmitStackTraceResponse *Plasma__SubmitStackTraceResponse);
	/// Web service operation 'VerifyAccountData' (return error code or SOAP_OK)
	virtual	int VerifyAccountData(_Plasma__VerifyAccountData *Plasma__VerifyAccountData, _Plasma__VerifyAccountDataResponse *Plasma__VerifyAccountDataResponse);
};
#endif
