Document: libspringdownloader
Title: Debian libspringdownloader Manual
Author: <insert document author here>
Abstract: This manual describes what libspringdownloader is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libspringdownloader/libspringdownloader.sgml.gz

Format: postscript
Files: /usr/share/doc/libspringdownloader/libspringdownloader.ps.gz

Format: text
Files: /usr/share/doc/libspringdownloader/libspringdownloader.text.gz

Format: HTML
Index: /usr/share/doc/libspringdownloader/html/index.html
Files: /usr/share/doc/libspringdownloader/html/*.html
