#ifndef LIBLIBSPRINGLOBBY_HEADERGUARD_CONFIG_H
#define LIBLIBSPRINGLOBBY_HEADERGUARD_CONFIG_H

#undef VERSION

/* the git tag / commit we build from */
#define VERSION "@LIBSPRINGLOBBY_REV@"

#endif /* LIBLIBSPRINGLOBBY_HEADERGUARD_CONFIG_H */
