/* soapPlasmaServiceSoap12Proxy.cpp
   Generated by gSOAP 2.7.9l from plasma.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#include "soapPlasmaServiceSoap12Proxy.h"

PlasmaServiceSoap12Proxy::PlasmaServiceSoap12Proxy()
{	PlasmaServiceSoap12Proxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

PlasmaServiceSoap12Proxy::PlasmaServiceSoap12Proxy(soap_mode iomode)
{	PlasmaServiceSoap12Proxy_init(iomode, iomode);
}

PlasmaServiceSoap12Proxy::PlasmaServiceSoap12Proxy(soap_mode imode, soap_mode omode)
{	PlasmaServiceSoap12Proxy_init(imode, omode);
}

void PlasmaServiceSoap12Proxy::PlasmaServiceSoap12Proxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "http://planet-wars.eu/PlasmaServer/PlasmaServiceSoap", NULL, NULL},
	{"ns1", "http://planet-wars.eu/PlasmaServer/", NULL, NULL},
	{"ns3", "http://planet-wars.eu/PlasmaServer/PlasmaServiceSoap12", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	if (!this->namespaces)
		this->namespaces = namespaces;
}

PlasmaServiceSoap12Proxy::~PlasmaServiceSoap12Proxy()
{ }

void PlasmaServiceSoap12Proxy::soap_noheader()
{	header = NULL;
}

const SOAP_ENV__Fault *PlasmaServiceSoap12Proxy::soap_fault()
{	return this->fault;
}

const char *PlasmaServiceSoap12Proxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *PlasmaServiceSoap12Proxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int PlasmaServiceSoap12Proxy::DeleteResource(_ns1__DeleteResource *ns1__DeleteResource, _ns1__DeleteResourceResponse *ns1__DeleteResourceResponse)
{	struct soap *soap = this;
	struct __ns3__DeleteResource soap_tmp___ns3__DeleteResource;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://planet-wars.eu/PlasmaServer/Service.asmx";
	soap_action = "http://planet-wars.eu/PlasmaServer/DeleteResource";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__DeleteResource.ns1__DeleteResource = ns1__DeleteResource;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__DeleteResource(soap, &soap_tmp___ns3__DeleteResource);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__DeleteResource(soap, &soap_tmp___ns3__DeleteResource, "-ns3:DeleteResource", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__DeleteResource(soap, &soap_tmp___ns3__DeleteResource, "-ns3:DeleteResource", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__DeleteResourceResponse)
		return soap_closesock(soap);
	ns1__DeleteResourceResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__DeleteResourceResponse->soap_get(soap, "ns1:DeleteResourceResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PlasmaServiceSoap12Proxy::DownloadFile(_ns1__DownloadFile *ns1__DownloadFile, _ns1__DownloadFileResponse *ns1__DownloadFileResponse)
{	struct soap *soap = this;
	struct __ns3__DownloadFile soap_tmp___ns3__DownloadFile;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://planet-wars.eu/PlasmaServer/Service.asmx";
	soap_action = "http://planet-wars.eu/PlasmaServer/DownloadFile";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__DownloadFile.ns1__DownloadFile = ns1__DownloadFile;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__DownloadFile(soap, &soap_tmp___ns3__DownloadFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__DownloadFile(soap, &soap_tmp___ns3__DownloadFile, "-ns3:DownloadFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__DownloadFile(soap, &soap_tmp___ns3__DownloadFile, "-ns3:DownloadFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__DownloadFileResponse)
		return soap_closesock(soap);
	ns1__DownloadFileResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__DownloadFileResponse->soap_get(soap, "ns1:DownloadFileResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PlasmaServiceSoap12Proxy::GetResourceData(_ns1__GetResourceData *ns1__GetResourceData, _ns1__GetResourceDataResponse *ns1__GetResourceDataResponse)
{	struct soap *soap = this;
	struct __ns3__GetResourceData soap_tmp___ns3__GetResourceData;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://planet-wars.eu/PlasmaServer/Service.asmx";
	soap_action = "http://planet-wars.eu/PlasmaServer/GetResourceData";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__GetResourceData.ns1__GetResourceData = ns1__GetResourceData;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__GetResourceData(soap, &soap_tmp___ns3__GetResourceData);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__GetResourceData(soap, &soap_tmp___ns3__GetResourceData, "-ns3:GetResourceData", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__GetResourceData(soap, &soap_tmp___ns3__GetResourceData, "-ns3:GetResourceData", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetResourceDataResponse)
		return soap_closesock(soap);
	ns1__GetResourceDataResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetResourceDataResponse->soap_get(soap, "ns1:GetResourceDataResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PlasmaServiceSoap12Proxy::GetResourceList(_ns1__GetResourceList *ns1__GetResourceList, _ns1__GetResourceListResponse *ns1__GetResourceListResponse)
{	struct soap *soap = this;
	struct __ns3__GetResourceList soap_tmp___ns3__GetResourceList;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://planet-wars.eu/PlasmaServer/Service.asmx";
	soap_action = "http://planet-wars.eu/PlasmaServer/GetResourceList";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__GetResourceList.ns1__GetResourceList = ns1__GetResourceList;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__GetResourceList(soap, &soap_tmp___ns3__GetResourceList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__GetResourceList(soap, &soap_tmp___ns3__GetResourceList, "-ns3:GetResourceList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__GetResourceList(soap, &soap_tmp___ns3__GetResourceList, "-ns3:GetResourceList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetResourceListResponse)
		return soap_closesock(soap);
	ns1__GetResourceListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetResourceListResponse->soap_get(soap, "ns1:GetResourceListResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PlasmaServiceSoap12Proxy::RegisterResource(_ns1__RegisterResource *ns1__RegisterResource, _ns1__RegisterResourceResponse *ns1__RegisterResourceResponse)
{	struct soap *soap = this;
	struct __ns3__RegisterResource soap_tmp___ns3__RegisterResource;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://planet-wars.eu/PlasmaServer/Service.asmx";
	soap_action = "http://planet-wars.eu/PlasmaServer/RegisterResource";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__RegisterResource.ns1__RegisterResource = ns1__RegisterResource;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__RegisterResource(soap, &soap_tmp___ns3__RegisterResource);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__RegisterResource(soap, &soap_tmp___ns3__RegisterResource, "-ns3:RegisterResource", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__RegisterResource(soap, &soap_tmp___ns3__RegisterResource, "-ns3:RegisterResource", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__RegisterResourceResponse)
		return soap_closesock(soap);
	ns1__RegisterResourceResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__RegisterResourceResponse->soap_get(soap, "ns1:RegisterResourceResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
