/* soapPlasmaServiceSoap12Proxy.h
   Generated by gSOAP 2.7.9l from plasma.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapPlasmaServiceSoap12Proxy_H
#define soapPlasmaServiceSoap12Proxy_H
#include "soapH.h"

class SOAP_CMAC PlasmaServiceSoap12Proxy : public soap
{ public:
	/// Endpoint URL of service 'PlasmaServiceSoap12Proxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	PlasmaServiceSoap12Proxy();
	/// Constructor with engine input+output mode control
	PlasmaServiceSoap12Proxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	PlasmaServiceSoap12Proxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~PlasmaServiceSoap12Proxy();
	/// Initializer used by constructor
	virtual	void PlasmaServiceSoap12Proxy_init(soap_mode imode, soap_mode omode);
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Web service operation 'DeleteResource' (return error code or SOAP_OK)
	virtual	int DeleteResource(_ns1__DeleteResource *ns1__DeleteResource, _ns1__DeleteResourceResponse *ns1__DeleteResourceResponse);
	/// Web service operation 'DownloadFile' (return error code or SOAP_OK)
	virtual	int DownloadFile(_ns1__DownloadFile *ns1__DownloadFile, _ns1__DownloadFileResponse *ns1__DownloadFileResponse);
	/// Web service operation 'GetResourceData' (return error code or SOAP_OK)
	virtual	int GetResourceData(_ns1__GetResourceData *ns1__GetResourceData, _ns1__GetResourceDataResponse *ns1__GetResourceDataResponse);
	/// Web service operation 'GetResourceList' (return error code or SOAP_OK)
	virtual	int GetResourceList(_ns1__GetResourceList *ns1__GetResourceList, _ns1__GetResourceListResponse *ns1__GetResourceListResponse);
	/// Web service operation 'RegisterResource' (return error code or SOAP_OK)
	virtual	int RegisterResource(_ns1__RegisterResource *ns1__RegisterResource, _ns1__RegisterResourceResponse *ns1__RegisterResourceResponse);
};
#endif
