/* soapContentServiceSoap12Proxy.h
   Generated by gSOAP 2.7.9l from plasma.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapContentServiceSoap12Proxy_H
#define soapContentServiceSoap12Proxy_H
#include "soapH.h"

class SOAP_CMAC ContentServiceSoap12Proxy : public soap
{ public:
	/// Endpoint URL of service 'ContentServiceSoap12Proxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	ContentServiceSoap12Proxy();
	/// Constructor with engine input+output mode control
	ContentServiceSoap12Proxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	ContentServiceSoap12Proxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~ContentServiceSoap12Proxy();
	/// Initializer used by constructor
	virtual	void ContentServiceSoap12Proxy_init(soap_mode imode, soap_mode omode);
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Web service operation 'DownloadFile' (return error code or SOAP_OK)
	virtual	int DownloadFile(_ns1__DownloadFile *ns1__DownloadFile, _ns1__DownloadFileResponse *ns1__DownloadFileResponse);
	/// Web service operation 'GetResourceData' (return error code or SOAP_OK)
	virtual	int GetResourceData(_ns1__GetResourceData *ns1__GetResourceData, _ns1__GetResourceDataResponse *ns1__GetResourceDataResponse);
	/// Web service operation 'GetResourceList' (return error code or SOAP_OK)
	virtual	int GetResourceList(_ns1__GetResourceList *ns1__GetResourceList, _ns1__GetResourceListResponse *ns1__GetResourceListResponse);
	/// Web service operation 'GetScriptMissionData' (return error code or SOAP_OK)
	virtual	int GetScriptMissionData(_ns1__GetScriptMissionData *ns1__GetScriptMissionData, _ns1__GetScriptMissionDataResponse *ns1__GetScriptMissionDataResponse);
	/// Web service operation 'NotifyMissionRun' (return error code or SOAP_OK)
	virtual	int NotifyMissionRun(_ns1__NotifyMissionRun *ns1__NotifyMissionRun, _ns1__NotifyMissionRunResponse *ns1__NotifyMissionRunResponse);
	/// Web service operation 'RegisterResource' (return error code or SOAP_OK)
	virtual	int RegisterResource(_ns1__RegisterResource *ns1__RegisterResource, _ns1__RegisterResourceResponse *ns1__RegisterResourceResponse);
	/// Web service operation 'SubmitMissionScore' (return error code or SOAP_OK)
	virtual	int SubmitMissionScore(_ns1__SubmitMissionScore *ns1__SubmitMissionScore, _ns1__SubmitMissionScoreResponse *ns1__SubmitMissionScoreResponse);
	/// Web service operation 'SubmitStackTrace' (return error code or SOAP_OK)
	virtual	int SubmitStackTrace(_ns1__SubmitStackTrace *ns1__SubmitStackTrace, _ns1__SubmitStackTraceResponse *ns1__SubmitStackTraceResponse);
};
#endif
